# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        vehicle:
            persistence:
                driver: orm
                model: App\Fleet\Domain\Vehicle
                provider: ~
                listener: ~
                finder: ~
                model_to_elastica_transformer:
                    service: App\Fleet\Infrastructure\Persistence\Elastic\VehicleToElasticaTransformer
                elastica_to_model_transformer:
                    service: App\Fleet\Infrastructure\Persistence\Elastic\ElasticaToVehicleTransformer
