<?php

declare(strict_types=1);

namespace App\Shared\Infrastructure\Doctrine\Migration;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250619112123 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE employee (id UUID NOT NULL, full_name_first_name VARCHAR(255) NOT NULL, full_name_last_name VARCHAR(255) NOT NULL, email_email VARCHAR(255) NOT NULL, employee_unit_id_uuid UUID NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE equipment (id UUID NOT NULL, equipment_template_id UUID DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D338D5836498FB9F ON equipment (equipment_template_id)');
        $this->addSql('CREATE TABLE equipment_category (id UUID NOT NULL, name_name VARCHAR(255) NOT NULL, parent_category_id UUID DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_368F9DE7796A8F92 ON equipment_category (parent_category_id)');
        $this->addSql('CREATE TABLE equipment_manufacturer (id UUID NOT NULL, name_name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE equipment_property (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, value VARCHAR(255) NOT NULL, equipment_id UUID NOT NULL, template_property_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_BB3198F8517FE9FE ON equipment_property (equipment_id)');
        $this->addSql('CREATE INDEX IDX_BB3198F85F6B0788 ON equipment_property (template_property_id)');
        $this->addSql('CREATE TABLE equipment_template (id UUID NOT NULL, name_name VARCHAR(255) NOT NULL, category_id UUID NOT NULL, manufacturer_id UUID NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A7A39BA512469DE2 ON equipment_template (category_id)');
        $this->addSql('CREATE INDEX IDX_A7A39BA5A23B42D ON equipment_template (manufacturer_id)');
        $this->addSql('CREATE TABLE equipment_template_equipment_template_property (equipment_template_id UUID NOT NULL, equipment_template_property_id INT NOT NULL, PRIMARY KEY(equipment_template_id, equipment_template_property_id))');
        $this->addSql('CREATE INDEX IDX_485944D96498FB9F ON equipment_template_equipment_template_property (equipment_template_id)');
        $this->addSql('CREATE INDEX IDX_485944D9D2E64AFD ON equipment_template_equipment_template_property (equipment_template_property_id)');
        $this->addSql('CREATE TABLE equipment_template_property (property_type VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, can_be_null BOOLEAN NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE fire_brigade_unit (id UUID NOT NULL, superior_unit_id UUID DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7AB0FDC222FBBFF0 ON fire_brigade_unit (superior_unit_id)');
        $this->addSql('CREATE TABLE resource (name VARCHAR(64) NOT NULL, PRIMARY KEY(name))');
        $this->addSql('CREATE TABLE role (name VARCHAR(64) NOT NULL, PRIMARY KEY(name))');
        $this->addSql('CREATE TABLE role_resource (role_id VARCHAR(64) NOT NULL, resource_id VARCHAR(64) NOT NULL, PRIMARY KEY(role_id, resource_id))');
        $this->addSql('CREATE INDEX IDX_96421227D60322AC ON role_resource (role_id)');
        $this->addSql('CREATE INDEX IDX_9642122789329D25 ON role_resource (resource_id)');
        $this->addSql('CREATE TABLE tenant (email VARCHAR NOT NULL, status VARCHAR(255) NOT NULL, password_hashed VARCHAR(255) NOT NULL, PRIMARY KEY(email))');
        $this->addSql('CREATE TABLE tenant_role (tenant_id VARCHAR NOT NULL, role_id VARCHAR(64) NOT NULL, PRIMARY KEY(tenant_id, role_id))');
        $this->addSql('CREATE INDEX IDX_1D06D0B99033212A ON tenant_role (tenant_id)');
        $this->addSql('CREATE INDEX IDX_1D06D0B9D60322AC ON tenant_role (role_id)');
        $this->addSql('CREATE TABLE vehicle (plate_number VARCHAR(12) NOT NULL, type VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, name_make VARCHAR(64) NOT NULL, name_model VARCHAR(64) NOT NULL, production_date_year INT NOT NULL, production_date_month INT DEFAULT NULL, assigned_unit_id_uuid UUID NOT NULL, PRIMARY KEY(plate_number))');
        $this->addSql('ALTER TABLE equipment ADD CONSTRAINT FK_D338D5836498FB9F FOREIGN KEY (equipment_template_id) REFERENCES equipment_template (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE equipment_category ADD CONSTRAINT FK_368F9DE7796A8F92 FOREIGN KEY (parent_category_id) REFERENCES equipment_category (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE equipment_property ADD CONSTRAINT FK_BB3198F8517FE9FE FOREIGN KEY (equipment_id) REFERENCES equipment (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE equipment_property ADD CONSTRAINT FK_BB3198F85F6B0788 FOREIGN KEY (template_property_id) REFERENCES equipment_template_property (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE equipment_template ADD CONSTRAINT FK_A7A39BA512469DE2 FOREIGN KEY (category_id) REFERENCES equipment_category (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE equipment_template ADD CONSTRAINT FK_A7A39BA5A23B42D FOREIGN KEY (manufacturer_id) REFERENCES equipment_manufacturer (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE equipment_template_equipment_template_property ADD CONSTRAINT FK_485944D96498FB9F FOREIGN KEY (equipment_template_id) REFERENCES equipment_template (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE equipment_template_equipment_template_property ADD CONSTRAINT FK_485944D9D2E64AFD FOREIGN KEY (equipment_template_property_id) REFERENCES equipment_template_property (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fire_brigade_unit ADD CONSTRAINT FK_7AB0FDC222FBBFF0 FOREIGN KEY (superior_unit_id) REFERENCES fire_brigade_unit (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE role_resource ADD CONSTRAINT FK_96421227D60322AC FOREIGN KEY (role_id) REFERENCES role (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE role_resource ADD CONSTRAINT FK_9642122789329D25 FOREIGN KEY (resource_id) REFERENCES resource (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tenant_role ADD CONSTRAINT FK_1D06D0B99033212A FOREIGN KEY (tenant_id) REFERENCES tenant (email) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tenant_role ADD CONSTRAINT FK_1D06D0B9D60322AC FOREIGN KEY (role_id) REFERENCES role (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE equipment DROP CONSTRAINT FK_D338D5836498FB9F');
        $this->addSql('ALTER TABLE equipment_category DROP CONSTRAINT FK_368F9DE7796A8F92');
        $this->addSql('ALTER TABLE equipment_property DROP CONSTRAINT FK_BB3198F8517FE9FE');
        $this->addSql('ALTER TABLE equipment_property DROP CONSTRAINT FK_BB3198F85F6B0788');
        $this->addSql('ALTER TABLE equipment_template DROP CONSTRAINT FK_A7A39BA512469DE2');
        $this->addSql('ALTER TABLE equipment_template DROP CONSTRAINT FK_A7A39BA5A23B42D');
        $this->addSql('ALTER TABLE equipment_template_equipment_template_property DROP CONSTRAINT FK_485944D96498FB9F');
        $this->addSql('ALTER TABLE equipment_template_equipment_template_property DROP CONSTRAINT FK_485944D9D2E64AFD');
        $this->addSql('ALTER TABLE fire_brigade_unit DROP CONSTRAINT FK_7AB0FDC222FBBFF0');
        $this->addSql('ALTER TABLE role_resource DROP CONSTRAINT FK_96421227D60322AC');
        $this->addSql('ALTER TABLE role_resource DROP CONSTRAINT FK_9642122789329D25');
        $this->addSql('ALTER TABLE tenant_role DROP CONSTRAINT FK_1D06D0B99033212A');
        $this->addSql('ALTER TABLE tenant_role DROP CONSTRAINT FK_1D06D0B9D60322AC');
        $this->addSql('DROP TABLE employee');
        $this->addSql('DROP TABLE equipment');
        $this->addSql('DROP TABLE equipment_category');
        $this->addSql('DROP TABLE equipment_manufacturer');
        $this->addSql('DROP TABLE equipment_property');
        $this->addSql('DROP TABLE equipment_template');
        $this->addSql('DROP TABLE equipment_template_equipment_template_property');
        $this->addSql('DROP TABLE equipment_template_property');
        $this->addSql('DROP TABLE fire_brigade_unit');
        $this->addSql('DROP TABLE resource');
        $this->addSql('DROP TABLE role');
        $this->addSql('DROP TABLE role_resource');
        $this->addSql('DROP TABLE tenant');
        $this->addSql('DROP TABLE tenant_role');
        $this->addSql('DROP TABLE vehicle');
    }
}
