<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250412110225 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE equipment (id UUID NOT NULL, equipment_template_id UUID DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D338D5836498FB9F ON equipment (equipment_template_id)');
        $this->addSql('CREATE TABLE equipment_equipment_property (equipment_id UUID NOT NULL, equipment_property_id INT NOT NULL, PRIMARY KEY(equipment_id, equipment_property_id))');
        $this->addSql('CREATE INDEX IDX_9E815FAA517FE9FE ON equipment_equipment_property (equipment_id)');
        $this->addSql('CREATE INDEX IDX_9E815FAA35D0E7CB ON equipment_equipment_property (equipment_property_id)');
        $this->addSql('CREATE TABLE equipment_property (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, value VARCHAR(255) NOT NULL, template_property_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_BB3198F85F6B0788 ON equipment_property (template_property_id)');
        $this->addSql('ALTER TABLE equipment ADD CONSTRAINT FK_D338D5836498FB9F FOREIGN KEY (equipment_template_id) REFERENCES equipment_template (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE equipment_equipment_property ADD CONSTRAINT FK_9E815FAA517FE9FE FOREIGN KEY (equipment_id) REFERENCES equipment (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE equipment_equipment_property ADD CONSTRAINT FK_9E815FAA35D0E7CB FOREIGN KEY (equipment_property_id) REFERENCES equipment_property (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE equipment_property ADD CONSTRAINT FK_BB3198F85F6B0788 FOREIGN KEY (template_property_id) REFERENCES equipment_template_property (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE equipment DROP CONSTRAINT FK_D338D5836498FB9F');
        $this->addSql('ALTER TABLE equipment_equipment_property DROP CONSTRAINT FK_9E815FAA517FE9FE');
        $this->addSql('ALTER TABLE equipment_equipment_property DROP CONSTRAINT FK_9E815FAA35D0E7CB');
        $this->addSql('ALTER TABLE equipment_property DROP CONSTRAINT FK_BB3198F85F6B0788');
        $this->addSql('DROP TABLE equipment');
        $this->addSql('DROP TABLE equipment_equipment_property');
        $this->addSql('DROP TABLE equipment_property');
    }
}
