<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250412094541 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE equipment_category (id UUID NOT NULL, parent_category_id UUID DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_368F9DE7796A8F92 ON equipment_category (parent_category_id)');
        $this->addSql('CREATE TABLE equipment_manufacturer (id UUID NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE equipment_template (id UUID NOT NULL, category_id UUID NOT NULL, manufacturer_id UUID NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A7A39BA512469DE2 ON equipment_template (category_id)');
        $this->addSql('CREATE INDEX IDX_A7A39BA5A23B42D ON equipment_template (manufacturer_id)');
        $this->addSql('CREATE TABLE equipment_template_equipment_template_property (equipment_template_id UUID NOT NULL, equipment_template_property_id INT NOT NULL, PRIMARY KEY(equipment_template_id, equipment_template_property_id))');
        $this->addSql('CREATE INDEX IDX_485944D96498FB9F ON equipment_template_equipment_template_property (equipment_template_id)');
        $this->addSql('CREATE INDEX IDX_485944D9D2E64AFD ON equipment_template_equipment_template_property (equipment_template_property_id)');
        $this->addSql('CREATE TABLE equipment_template_property (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, property_type VARCHAR(255) NOT NULL, value VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE equipment_category ADD CONSTRAINT FK_368F9DE7796A8F92 FOREIGN KEY (parent_category_id) REFERENCES equipment_category (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE equipment_template ADD CONSTRAINT FK_A7A39BA512469DE2 FOREIGN KEY (category_id) REFERENCES equipment_category (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE equipment_template ADD CONSTRAINT FK_A7A39BA5A23B42D FOREIGN KEY (manufacturer_id) REFERENCES equipment_manufacturer (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE equipment_template_equipment_template_property ADD CONSTRAINT FK_485944D96498FB9F FOREIGN KEY (equipment_template_id) REFERENCES equipment_template (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE equipment_template_equipment_template_property ADD CONSTRAINT FK_485944D9D2E64AFD FOREIGN KEY (equipment_template_property_id) REFERENCES equipment_template_property (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE employee ALTER email_email TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE employee ALTER email_email SET NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE equipment_category DROP CONSTRAINT FK_368F9DE7796A8F92');
        $this->addSql('ALTER TABLE equipment_template DROP CONSTRAINT FK_A7A39BA512469DE2');
        $this->addSql('ALTER TABLE equipment_template DROP CONSTRAINT FK_A7A39BA5A23B42D');
        $this->addSql('ALTER TABLE equipment_template_equipment_template_property DROP CONSTRAINT FK_485944D96498FB9F');
        $this->addSql('ALTER TABLE equipment_template_equipment_template_property DROP CONSTRAINT FK_485944D9D2E64AFD');
        $this->addSql('DROP TABLE equipment_category');
        $this->addSql('DROP TABLE equipment_manufacturer');
        $this->addSql('DROP TABLE equipment_template');
        $this->addSql('DROP TABLE equipment_template_equipment_template_property');
        $this->addSql('DROP TABLE equipment_template_property');
        $this->addSql('ALTER TABLE employee ALTER email_email TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE employee ALTER email_email DROP NOT NULL');
    }
}
